# --- Build Stage ---
FROM node:20-alpine AS builder
WORKDIR /app
COPY ../server/package*.json ./
RUN npm ci
COPY ../server/ .
RUN npm run build

# --- Production Runner Stage ---
FROM node:20-alpine AS runner
WORKDIR /app
ENV NODE_ENV=production
COPY --from=builder /app/package*.json ./
COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app/dist ./dist

EXPOSE 5000
CMD ["npm", "run", "start"]
